# Generated by Django 5.0.6 on 2024-12-13 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_alter_event_description_alter_event_participants"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="date",
            field=models.DateField(db_index=True),
        ),
    ]
